#
# General Makefile
#

all:
	cd clist && make
	cd draw_ruler && make
	cd insertion_sort && make
	cd linear_sum && make
	cd list && make
	cd reverse_array && make
	cd singly_linkedlist && make

.PHONY: all clean

clean:
	cd clist && make clean
	cd draw_ruler && make clean
	cd insertion_sort && make clean
	cd linear_sum && make clean
	cd list && make clean
	cd reverse_array && make clean
	cd singly_linkedlist && make clean

