#
# General Makefile
#

all:
	cd hashcode_folding && make
	cd cyclic_shift_hashcode && make
	cd polynomial_hashcode && make

.PHONY: all clean

clean:
	cd hashcode_folding && make clean
	cd cyclic_shift_hashcode && make clean
	cd polynomial_hashcode && make clean

