#
# General Makefile
#

all:
	cd inorder_insertion && make
	cd linked_binary_tree && make
	cd number_of_descendants && make
	cd template_eulertour && make

.PHONY: all clean

clean:
	cd inorder_insertion && make clean
	cd linked_binary_tree && make clean
	cd number_of_descendants && make clean
	cd template_eulertour && make clean

