#
# General Makefile
#

all:
	cd adapt_pq_location_aware && make
	cd btm_up_heap_constrn_lvl_ord_trv && make
	cd heap_priority_queue && make
	cd list_priority_queue && make

.PHONY: all clean

clean:
	cd adapt_pq_location_aware && make clean
	cd btm_up_heap_constrn_lvl_ord_trv && make clean
	cd heap_priority_queue && make clean
	cd list_priority_queue && make clean

